#![doc = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/", "README.md"))]
#![cfg_attr(feature = "no_std", no_std)]

// `no_std` is the attribute and nothing more. The crate's own code is `core`
// only at every width and under every feature: the one lock, at `u128_index`,
// is a `Mutex` under `std` and a spin lock without it, and the cell `const`
// fills on first read is a `OnceLock` under `std` and a state byte without it.
// Neither feature refuses the other.

// Exactly one index width is selected, so the crate is written once against a
// type alias for it rather than generated by a macro per width.
//
// It used to be a macro, and the macro was the reason for most of the file.
// Nothing here varies per width except the integer type and, for `u128`, the
// absence of an atomic to keep it in, and an alias says all of that. What the
// macro cost was the usual price of generated code: four `cfg` blocks choosing
// between two expansions that differed only in a commented-out `const`, each
// carrying a `panic!` guarded by the negation of the `cfg` it was already
// inside, so it could never run.

// ---------------------------------------------------------------------------
// Width selection.
// ---------------------------------------------------------------------------

// The width features are mutually exclusive: each defines the same items, so
// enabling two defines them twice. Without this guard the failure is a wall of
// E0428 duplicate-definition errors naming internals, with nothing pointing at
// the feature flags that caused it, which is what `cargo build --all-features`
// produced.
#[cfg(any(
    all(feature = "u8_index", feature = "u16_index"),
    all(feature = "u8_index", feature = "u32_index"),
    all(feature = "u8_index", feature = "u64_index"),
    all(feature = "u8_index", feature = "u128_index"),
    all(feature = "u8_index", feature = "usize_index"),
    all(feature = "u16_index", feature = "u32_index"),
    all(feature = "u16_index", feature = "u64_index"),
    all(feature = "u16_index", feature = "u128_index"),
    all(feature = "u16_index", feature = "usize_index"),
    all(feature = "u32_index", feature = "u64_index"),
    all(feature = "u32_index", feature = "u128_index"),
    all(feature = "u32_index", feature = "usize_index"),
    all(feature = "u64_index", feature = "u128_index"),
    all(feature = "u64_index", feature = "usize_index"),
    all(feature = "u128_index", feature = "usize_index"),
))]
compile_error!(
    "more than one index-width feature is enabled. Exactly one of u8_index, u16_index, \
     u32_index, u64_index, u128_index or usize_index selects the width of the rolling \
     index, and they cannot coexist. The default is u16_index, so a second one usually \
     means default-features was left on: set `default-features = false` alongside the \
     width you want. `--all-features` cannot work on this crate for the same reason."
);

// Equally, selecting none leaves the crate with no index type at all, and the
// errors are then about a missing `RUID` rather than about the flags.
#[cfg(not(any(
    feature = "u8_index",
    feature = "u16_index",
    feature = "u32_index",
    feature = "u64_index",
    feature = "u128_index",
    feature = "usize_index",
)))]
compile_error!(
    "no index-width feature is enabled, so there is no rolling index type to use. \
     Enable exactly one of u8_index, u16_index, u32_index, u64_index, u128_index or \
     usize_index. The default is u16_index; this usually means default-features was \
     turned off without naming a replacement."
);

// Each alias excludes the widths named before it, so at most one is ever
// defined. That is not about correctness, since two widths is already refused
// above; it is about which error the reader sees. Without it, enabling two
// produces a duplicate-definition error for every item as well, and the wall of
// E0428 arrives first and buries the one message that says which flags caused
// it. Leaving `default-features` on while naming a second width is the common
// way to get here.

/// The integer the rolling index is made of, chosen by the width feature.
#[cfg(feature = "u8_index")]
pub type Idx = u8;
/// The integer the rolling index is made of, chosen by the width feature.
#[cfg(all(feature = "u16_index", not(any(feature = "u8_index"))))]
pub type Idx = u16;
/// The integer the rolling index is made of, chosen by the width feature.
#[cfg(all(feature = "u32_index", not(any(feature = "u8_index", feature = "u16_index"))))]
pub type Idx = u32;
/// The integer the rolling index is made of, chosen by the width feature.
#[cfg(all(
    feature = "u64_index",
    not(any(feature = "u8_index", feature = "u16_index", feature = "u32_index"))
))]
pub type Idx = u64;
/// The integer the rolling index is made of, chosen by the width feature.
#[cfg(all(
    feature = "u128_index",
    not(any(
        feature = "u8_index",
        feature = "u16_index",
        feature = "u32_index",
        feature = "u64_index"
    ))
))]
pub type Idx = u128;
/// The integer the rolling index is made of, chosen by the width feature.
#[cfg(all(
    feature = "usize_index",
    not(any(
        feature = "u8_index",
        feature = "u16_index",
        feature = "u32_index",
        feature = "u64_index",
        feature = "u128_index"
    ))
))]
pub type Idx = usize;

mod counter;
pub mod declare;
mod index;
#[cfg(all(feature = "ruid_type", feature = "const"))]
mod lazy;
mod width;

pub use counter::{Counter, Exhaustion, Refuse, Wrap};
#[cfg(feature = "no_alloc")]
pub use index::fill_rolling_idx;
pub use index::{reset_rolling_idx, rolling_idx, Policy, _ROLLING_IDX_MAX, ROLLING_IDX};
pub use width::Width;

#[cfg(feature = "ruid_type")]
mod ruid;
#[cfg(feature = "ruid_type")]
pub use ruid::{Derived, Provenance, Rolled, RUID};

// `RUID` holds an integer, or a cell that fills with one, and both are already
// `Send` and `Sync`, so the compiler establishes this on its own. It used to be
// asserted with two `unsafe impl`s behind an `async` feature. They were not
// needed, and an `unsafe impl` that is not needed is worse than none, because
// it would go on asserting the property after a change that stopped it being
// true.
//
// The `async` feature is kept so that naming it is not an error, and gates
// nothing.
#[cfg(feature = "ruid_type")]
const _: () = {
    const fn require<T: Send + Sync>() {}
    require::<RUID<Rolled>>();
    require::<RUID<Derived>>();
};

#[cfg(test)]
mod tests;
